export const INDUSTRIES = [
  { name: "Oil", count: 168692 },
  { name: "General Contractors", count: 155466 },
  { name: "Land Surveyors", count: 135586 },
  { name: "Auto Repair", count: 120435 },
  { name: "Electricians", count: 108746 },
  { name: "Hauling", count: 101761 },
  { name: "Air Conditioning", count: 94316 },
  { name: "Roofing Contractors", count: 84572 },
  { name: "Auto Parts", count: 83772 },
  { name: "Carpet", count: 76026 },
  { name: "Commercial Janitorial", count: 75791 },
  { name: "Landscaping", count: 73693 },
  { name: "Altering & Remodeling", count: 73587 },
  { name: "Fasteners", count: 72387 },
  { name: "Appliance Repair", count: 63575 },
  { name: "Kitchen Remodeling", count: 54949 },
  { name: "Engineering", count: 54648 },
  { name: "Commercial Lighting", count: 50015 },
  { name: "Furnaces", count: 47889 },
  { name: "Foundation Contractors", count: 45171 },
  { name: "Excavating Contractors", count: 43736 },
  { name: "Architects", count: 43673 },
  { name: "Cabinetry", count: 43042 },
  { name: "Glass", count: 42806 },
  { name: "Signs", count: 41899 },
  { name: "Restoration", count: 40031 },
  { name: "Building Materials", count: 39586 },
  { name: "Paving", count: 39064 },
  { name: "Vehicle Engineering", count: 38695 },
  { name: "Funeral Homes", count: 37821 },
  { name: "Epoxy Flooring", count: 36476 },
  { name: "Bathroom Remodeling", count: 35932 },
  { name: "Handyman Services", count: 33932 },
  { name: "Concrete Contractors", count: 33342 },
  { name: "HVAC", count: 31646 },
  { name: "Grinding", count: 31420 },
  { name: "Septic", count: 31391 },
  { name: "Heavy Equipment Rentals", count: 30822 },
  { name: "Dental Labs", count: 30430 },
  { name: "Pool Plastering", count: 28482 },
  { name: "Trailers", count: 27886 },
  { name: "Drywall Contractors", count: 26579 },
  { name: "Upholstery", count: 26475 },
  { name: "Transmission Repair", count: 26430 },
  { name: "Tile Contractors", count: 25423 },
  { name: "Metal Fabrication", count: 24579 },
  { name: "Manufactured Products", count: 24218 },
  { name: "Aviation", count: 23602 },
  { name: "Decks & Patios", count: 23354 },
  { name: "Flooring Contractors", count: 22922 },
  { name: "Brick Layers", count: 22469 },
  { name: "Windows", count: 22282 },
  { name: "Welders", count: 22240 },
  { name: "Diesel Repair", count: 21189 },
  { name: "Farm Equipment", count: 20547 },
  { name: "Gutters & Downspouts", count: 19935 },
  { name: "Ornamental Iron", count: 19921 },
  { name: "Sash & Door", count: 18914 },
  { name: "Tools", count: 18827 },
  { name: "Siding", count: 18656 },
  { name: "Asphalt", count: 17709 },
  { name: "Freight Forwarding", count: 17570 },
  { name: "Commercial Plumbing", count: 16796 },
  { name: "Fencing", count: 16789 },
  { name: "Wind Power", count: 16734 },
  { name: "Logistics", count: 16052 },
  { name: "Automation", count: 15557 },
  { name: "Insulation Contractors", count: 15030 },
  { name: "Truck Repair", count: 14176 },
  { name: "Abrasives", count: 13700 },
  { name: "Snow Removal", count: 13219 },
  { name: "Analytical Labs", count: 13088 },
  { name: "Chemicals", count: 12773 },
  { name: "Machine Shops", count: 12472 },
  { name: "Masonry Contractors", count: 12281 },
  { name: "Demolition Contractors", count: 11815 },
  { name: "Solar", count: 11809 },
  { name: "Seal Coating", count: 11397 },
  { name: "Contract Manufacturing", count: 11335 },
  { name: "Foundation Repair", count: 2655 },
  { name: "Boat Maintenance", count: 10607 },
  { name: "Home Theater Installations", count: 9980 },
  { name: "Woodworking", count: 9952 },
  { name: "Refrigeration", count: 9766 },
  { name: "Lumber", count: 9600 },
  { name: "Restaurant Equipment", count: 9498 },
  { name: "Power Washing", count: 9211 },
  { name: "Roll Off Containers", count: 9012 },
  { name: "Scaffolding", count: 8834 },
  { name: "Exterior Coating", count: 8027 },
  { name: "Sand & Gravel", count: 7992 },
  { name: "Plastic Products", count: 7761 },
  { name: "Marble & Granite", count: 7740 },
  { name: "Countertops", count: 7693 },
  { name: "Green Building Design", count: 7566 },
  { name: "Land Surveying", count: 7564 },
  { name: "Motorsports", count: 7051 },
  { name: "Classic Car Restoration", count: 6878 },
  { name: "Steel Buildings", count: 6555 },
  { name: "Concrete", count: 6328 },
  { name: "Drilling", count: 6311 },
  { name: "Elevators", count: 6172 },
  { name: "Plastering Contractors", count: 5935 },
  { name: "Cylinders", count: 5766 },
  { name: "Boat Repair", count: 5620 },
  { name: "Cranes", count: 5393 },
  { name: "Awnings & Canopies", count: 5315 },
  { name: "Textiles", count: 4842 },
  { name: "Fireplaces", count: 4599 },
  { name: "Structural Engineering", count: 3959 },
  { name: "Metal Fabrications", count: 3904 },
  { name: "Forklifts", count: 3787 },
  { name: "Tanks", count: 3691 },
  { name: "Sandblasting Contractors", count: 3649 },
  { name: "Compressors", count: 3244 },
  { name: "Semiconductor Devices", count: 3141 },
  { name: "Architectural Engineering", count: 3023 },
  { name: "Irrigation Contractors", count: 2983 },
  { name: "Plastic & Plastic Products", count: 2786 },
  { name: "Materials Engineering", count: 2622 },
  { name: "Aircraft Maintenance", count: 2421 },
  { name: "Portable Buildings", count: 2405 },
  { name: "Bearings", count: 2366 },
  { name: "Industrial Development", count: 2196 },
  { name: "Pond Construction", count: 2134 },
  { name: "Racks", count: 2107 },
  { name: "Horse Boarding", count: 1830 },
  { name: "Hydraulics", count: 1739 },
  { name: "Stair Builders", count: 1476 },
  { name: "Boilers", count: 1350 },
  { name: "Home Remodeling Contractors", count: 1232 },
  { name: "Sheet Metal", count: 1176 },
  { name: "Powder Coating", count: 1136 },
  { name: "Foam", count: 1125 },
  { name: "Pole Barns", count: 1099 },
  { name: "Fiberglass", count: 949 },
  { name: "Lighting Systems", count: 914 },
  { name: "Professional Engineers", count: 898 },
  { name: "Carpet Cleaners", count: 779 },
  { name: "Fiber Glass", count: 641 },
  { name: "Raised Floors", count: 418 },
  { name: "Drive Shafts", count: 344 },
  { name: "Janitorial Service", count: 341 },
  { name: "Diesel Engine Fuel Injection Parts", count: 192 },
  { name: "Auto Restoration", count: 191 },
  { name: "Acoustical Engineering", count: 178 },
  { name: "Airlines", count: 157 },
  { name: "Mud Jacking", count: 132 },
  { name: "Louvers", count: 128 },
  { name: "Deck Builders", count: 105 },
  { name: "Canopies", count: 42 },
  { name: "Ceramic Paintings", count: 41 },
  { name: "Aircraft", count: 39 },
  { name: "Pound Construction", count: 37 },
  { name: "Compressor", count: 31 },
  { name: "Boring Equipment", count: 28 },
  { name: "Remodeling Contractors", count: 12 }
].map(industry => ({
  ...industry,
  slug: industry.name.toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .trim()
}));